apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: api-app
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/danielmoisa/api-deploy-tf-k8s
        targetRevision: main
        path: k8s # path to your k8s manifests
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
